export const types = {
  SET_USERNAME: 'SET_USERNAME',
  ADD_NEW_ARTICLE: 'ADD_NEW_ARTICLE',
  REMOVE_ARTICLE: 'REMOVE_ARTICLE',
  ADD_NEW_ARTICLE_TEXT: 'ADD_NEW_ARTICLE_TEXT',
  ADD_USER: 'ADD_USER',
};
